title: Cheng Wang's Homepage
page-top-title: Cheng Wang
top-section-bg-text: Be what you wanna be
home-subtitle: Cheng Wang&ensp;|&ensp;王铖
copyright-text: '&copy; Cheng Wang 2023-2025. All Rights Reserved.'
